// Code generated by protoc-gen-go.
// source: signal.proto
// DO NOT EDIT!

/*
Package signal is a generated protocol buffer package.

It is generated from these files:
	signal.proto

It has these top-level messages:
	Signal
	Header
*/
package signal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Signal 信令结构定义
type Signal struct {
	// 信令值,uint32
	Signal uint32 `protobuf:"varint,1,opt,name=signal" json:"signal,omitempty"`
	// 序列号
	Sequence int64 `protobuf:"varint,2,opt,name=sequence" json:"sequence,omitempty"`
	// 版本号
	Version uint32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	// 信令头扩展
	Headers *Header `protobuf:"bytes,4,opt,name=headers" json:"headers,omitempty"`
	// 信令内容
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Signal) Reset()                    { *m = Signal{} }
func (m *Signal) String() string            { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()               {}
func (*Signal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Signal) GetSignal() uint32 {
	if m != nil {
		return m.Signal
	}
	return 0
}

func (m *Signal) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Signal) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Signal) GetHeaders() *Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Signal) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Header 信令头定义
type Header struct {
	// 头定义
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// 值
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Signal)(nil), "signal.Signal")
	proto.RegisterType((*Header)(nil), "signal.Header")
}

func init() { proto.RegisterFile("signal.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x8f, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x86, 0xd9, 0xd4, 0x35, 0x27, 0x8b, 0x18, 0x22, 0x96, 0x4e, 0x8b, 0xa7, 0x3d, 0x49, 0xd4,
	0x4b, 0x74, 0xde, 0x9e, 0x60, 0xcb, 0xa1, 0x24, 0xd1, 0x72, 0x55, 0xe8, 0x3d, 0x7a, 0xe0, 0x68,
	0x57, 0xbb, 0xfd, 0xdf, 0x3f, 0x33, 0xf0, 0x0d, 0xa4, 0xb6, 0xbc, 0xd5, 0xa6, 0xca, 0x9f, 0x6d,
	0xd3, 0x35, 0xc8, 0x3d, 0x65, 0x1f, 0x06, 0xfc, 0xec, 0x22, 0x6e, 0x61, 0x2c, 0x05, 0x93, 0x4c,
	0x2d, 0xf5, 0x48, 0xb8, 0x83, 0xb9, 0xa5, 0x57, 0x4f, 0xf5, 0x95, 0xc4, 0x4c, 0x32, 0x15, 0xe8,
	0x3f, 0xa3, 0x80, 0x78, 0xa0, 0xd6, 0x96, 0x4d, 0x2d, 0x02, 0x77, 0x34, 0x21, 0x2a, 0x88, 0xef,
	0x64, 0x0a, 0x6a, 0xad, 0x08, 0x25, 0x53, 0x8b, 0xc3, 0x2a, 0x1f, 0x05, 0x4e, 0xae, 0xd6, 0xd3,
	0x18, 0x11, 0xc2, 0xc2, 0x74, 0x46, 0x44, 0x92, 0xa9, 0x54, 0xbb, 0x9c, 0xed, 0x81, 0xfb, 0x35,
	0x5c, 0x43, 0xf0, 0xa0, 0xb7, 0x53, 0x4a, 0xf4, 0x2f, 0xe2, 0x06, 0xa2, 0xc1, 0x54, 0xbd, 0x97,
	0x49, 0xb4, 0x87, 0x0b, 0x77, 0x7f, 0x1d, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x33, 0xc4,
	0x0f, 0xe7, 0x00, 0x00, 0x00,
}
